version: '2'
services:
    microservicetest-app:
        image: microservicetest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://microservicetest-mysql:3306/microservicetest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    microservicetest-mysql:
        extends:
            file: mysql.yml
            service: microservicetest-mysql
